POST http://localhost:3000/api/patients
Content-Type: application/json


{
  "name": "Anna Test",
  "dateOfBirth": "2000-09-17",
  "ssn": "3213131abc",
  "gender": "female",
  "occupation": "Boxer"
}

