POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlaGUiLCJpZCI6IjY4N2EyMDc3YjQxMzY2Mzg4YzY2NmZhNSIsImlhdCI6MTc1MjgzODcyNiwiZXhwIjoxNzUyODQyMzI2fQ.H_OOCwC-YAmj6UeXaFZg_HSIyHvjpBo-CVt7VgtHZxA

{
  "title": "waowao",
  "author": "Anna wa",
  "url": "wao.com",
  "likes": 342  
}

