POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "midnight sit",
  "author": "Rufelius Davidson",
  "url": "rufeliies.com",
  "likes": 5132,
  "user": "68765f9a8d035a03be3e2d66"
  
}

